// swift-tools-version: 5.5

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "Memoria",
    platforms: [
        .iOS("15.2")
    ],
    products: [
        .iOSApplication(
            name: "Memoria",
            targets: ["AppModule"],
            bundleIdentifier: "ca.sagarp.Memoria",
            teamIdentifier: "LL6476HKHT",
            displayVersion: "1.0",
            bundleVersion: "1",
            iconAssetName: "AppIcon",
            accentColorAssetName: "AccentColor",
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            capabilities: [
                .localNetwork(purposeString: "Allows connection to your hosted server", bonjourServiceTypes: []),
                .photoLibrary(purposeString: "Allows access to your library to sync them to your hosted server")
            ]
        )
    ],
    dependencies: [
        .package(url: "https://github.com/Alamofire/Alamofire.git", "5.5.0"..<"6.0.0"),
        .package(url: "https://github.com/sagar5534/KeychainAccess.git", "4.2.2"..<"5.0.0"),
        .package(url: "https://github.com/lorenzofiamingo/swiftui-cached-async-image", "2.0.0"..<"3.0.0")
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            dependencies: [
                .product(name: "Alamofire", package: "Alamofire"),
                .product(name: "KeychainAccess", package: "KeychainAccess"),
                .product(name: "CachedAsyncImage", package: "swiftui-cached-async-image")
            ],
            path: ".",
            resources: [
                .process("Resources")
            ]
        )
    ]
)
