// swift-tools-version: 5.5

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "Memoria",
    platforms: [
        .iOS("15.2")
    ],
    products: [
        .iOSApplication(
            name: "Memoria",
            targets: ["AppModule"],
            bundleIdentifier: "ca.sagarp.Memoria",
            teamIdentifier: "LL6476HKHT",
            displayVersion: "1.0",
            bundleVersion: "1",
            iconAssetName: "AppIcon",
            accentColorAssetName: "AccentColor",
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ]
        )
    ],
    dependencies: [
        .package(url: "https://github.com/Alamofire/Alamofire.git", .branch("master")),
        .package(url: "https://github.com/kishikawakatsumi/KeychainAccess.git", .branch("master"))
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            dependencies: [
                .product(name: "Alamofire", package: "alamofire"),
                .product(name: "KeychainAccess", package: "keychainaccess")
            ],
            path: ".",
            resources: [
                .process("Resources")
            ]
        )
    ]
)